### ISSUE TITLE
Add keyboard shortcut bar

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#152]
Most soft keyboards don't have arrow keys, escape, tab, ctrl, alt, shift, meta, etc. and using a terminal is rather unwieldy, so there should be an optional keyboard extension bar that'd sit on the screen bottom and provide those keys, like e.g. here

![iPad screenshot](https://user-images.githubusercontent.com/5412095/30271998-be41aea2-96f2-11e7-9520-527351c236c8.png)

**Comment by MightyPork** [comment]
there's an app for this called Hacker Keyboard for Android

**Comment by c-probably-archived20260718** [comment]
on iOS there isn't

**Comment by MightyPork** [comment]
well you know who's implementing that then :p
maybe this could be combined with the debug bar idea :thinking:

**Comment by c-probably-archived20260718** [comment]
Added a basic keyboard bar (only on iOS) directly below the screen (can't use `position: fixed` because that's just shoved under the keyboard)
<img width="475" alt="iPhone" src="https://user-images.githubusercontent.com/5412095/30768339-3b73d01e-a006-11e7-8c0d-82213f3e224c.png">
![iPad](https://user-images.githubusercontent.com/5412095/30768345-447163fc-a006-11e7-8e1b-219fa9cd5071.png)

I also moved the fit-to-screen button above the screen (and forgot to say so in the commit). This is because for whatever reason page scrolling does not work at all on an iPhone, so you can't scroll down to even press the fit-to-screen button, though horizontal scrolling works. Moving it up allows access to most or all of the page depending on the screen height

**Comment by MightyPork** [comment]
moving that button up is a good addition! I think this can be closed, seems to work ok
